# This is a basic workflow to help you get started with Actions

name: status-check curl

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '*/5 * * * *'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  http_https:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
       protocols:
       - http
       - https
       sites:
          - '4sale.kaovilai.pw.'
          - 'address.kaovilai.pw.'
          - 'amazon.kaovilai.pw.'
          - 'blog.kaovilai.pw.'
          - 'cal.kaovilai.pw.'
          - 'calendar.kaovilai.pw.'
          - 'contact.4sale.kaovilai.pw.'
          - 'contact.kaovilai.pw.'
          - 'directory.ncsu.kaovilai.pw.'
          - 'facebook.kaovilai.pw.'
          - 'fb.kaovilai.pw.'
          - 'github.kaovilai.pw.'
          - 'home.kaovilai.pw.'
          - 'in.kaovilai.pw.'
          - 'kaovilai.pw.'
          - 'l.kaovilai.pw.'
          - 'legacy.kaovilai.pw.'
          - 'li.kaovilai.pw.'
          - 'linkedin.kaovilai.pw.'
          - 'links.kaovilai.pw.'
          - 'mail.kaovilai.pw.'
          - 'mail.scissor.kaovilai.pw.'
          - 'mymoodle.kaovilai.pw.'
          - 'new.kaovilai.pw.'
          - 'phone.kaovilai.pw.'
          - 'print.kaovilai.pw.'
          - 'quora.kaovilai.pw.'
          - 'r.kaovilai.pw.'
          - 'referrals.kaovilai.pw.'
          - 'rel200project.ncsu.kaovilai.pw.'
          - 'resume.kaovilai.pw.'
          - 's.kaovilai.pw.'
          - 'scissor.kaovilai.pw.'
          - 'scissorapps.kaovilai.pw.'
          - 'speedtest.kaovilai.pw.'
          - 'temjai.kaovilai.pw.'
          - 'textresume.kaovilai.pw.'
          - 'wolfprint.kaovilai.pw.'
          - 'www.kaovilai.pw.'
          - 'tig.pw.'
          - 'adjs.tig.pw.'
          - 'everything.tig.pw.'
          - 'github.tig.pw.'
          - 'blog.tig.pw.'
          - 'contact.tig.pw.'
          - 'linkedin.tig.pw.'
          - 'lkin.tig.pw.'
          - 'meet.tig.pw.'
          - 'resume.tig.pw.'
          - 'twitter.tig.pw.'

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: curl ${{ matrix.protocols }}://${{ matrix.sites }}
        
  http:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
       protocols:
       - http
       sites:
          - 'a.kaovilai.pw.'
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: curl ${{ matrix.protocols }}://${{ matrix.sites }}

